/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        primary: "#6f4627",
        "primary-container": "#8b5e3c",
        "primary-container-hover": "#744e30",
        "primary-hover": "#5a371e",
        "primary-active": "#58371e",
        "primary-soft": "#f5efea",
        "primary-header": "#efe8e1",
        "primary-ink": "#2a160a",
        "on-primary": "#ffffff",
        secondary: "#5e5e5b",
        background: "#F9F7F2",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f4f3f3",
        "surface-container": "#eeeeee",
        "outline-variant": "#d5c3b8",
        "on-surface": "#1a1c1c",
        "on-surface-variant": "#51443c",
        "surface-dark": "#1e222d",
        "surface-dark-deep": "#181b24",
        "surface-dark-muted": "#252a37",
        "surface-dark-panel": "#232736",
        "surface-dark-table": "#272c3a",
        "surface-warm": "#faf7f4",
        "surface-warm-muted": "#f5f3f0",
        "warm-ink": "#1c1410",
        "warm-text": "#30231e",
        "warm-muted": "#746a64",
        "status-new-cell": "#eef5ff",
        "status-new-cell-dark": "#1a2536",
        "status-new-cell-hover": "#e2edff",
        "status-progress-cell": "#fef8ec",
        "status-progress-cell-dark": "#28221b",
        "status-progress-cell-hover": "#fdf0d9",
        "status-complete-cell": "#ebfbf3",
        "status-complete-cell-dark": "#182821",
        "status-complete-cell-hover": "#ddf7e9",
        "status-cancel-cell": "#fdf2f2",
        "status-cancel-cell-dark": "#2a1c1e",
        "status-cancel-cell-hover": "#fbe4e4",
        leather: {
          50: "#FDF8F3",
          100: "#F7EBE0",
          200: "#EBD4C0",
          500: "#8b5e3c",
          600: "#6f4627",
          700: "#52321C",
          800: "#3D2413",
        },
        darkText: "#1a1c1c",
        mutedText: "#51443c",
        borderLeather: "#d5c3b8",
      },
      fontFamily: {
        sans: ["'Be Vietnam Pro'", "'Inter'", "system-ui", "sans-serif"],
        serif: ["'Be Vietnam Pro'", "'Inter'", "sans-serif"],
        headline: ["'Be Vietnam Pro'", "'Inter'", "sans-serif"],
      },
    },
  },
  plugins: [],
};
